### ISSUE TITLE
Does 2.0.0 introduce any breaking changes?

### ISSUE THREAD

**Issue by ryanblock** [continuationlabs/zipit#2]
Hey there! Last month 2.0.0 was released. A quick look over the changes in 2.0.0 indicate that most of the refactoring was done in tests. There doesn't appear to show signals of any potentially breaking changes, but the bump of the major implies there are.

Since we don't have a changelog or other information to go by, I'm opening this here issue. So, any aspects of 2.0.0 that introduce breaking changes?

**Comment by cjihrig** [comment]
Hello! There are no breaking changes to the API. The major bump was to drop support for Node 4 and 6. I should have called that out in the [release summary](https://github.com/cjihrig/zipit/releases/tag/v2.0.0). I'll do a better job of that in the future, now that I know people other than me are actually using this thing 😄

**Comment by ryanblock** [comment]
Sweet! We definitely use it, and appreciate its maintenance. 💕
